import { GlobalConfig } from './config.model';

export interface Theme {
    label: string;
    value: string;
    colors: Partial<GlobalConfig>;
}

export const THEMES: Theme[] = [
    {
        label: 'Purple (Default)',
        value: 'purple',
        colors: {
            colorPrimaryApp: '#6750a4',
            colorPrimary: '#6750a4',
            colorOnPrimary: '#ffffff',
            colorSurface: '#1c1b1f',
            colorOnSurface: '#49454e',
            colorSurfaceVariant: '#fef7ff',
            colorOnSurfaceVariant: '#1c1b1f',
            colorPrimaryContainer: '#eaddff',
            colorOnPrimaryContainer: '#21005e',
            colorSecondaryContainer: '#e8def8',
            colorOnSecondaryContainer: '#1d192b',
            colorBackground: '#fef7ff',
            colorSurfaceContainerHigh: '#ece6f0',
            colorSurfaceContainerLow: '#f7f2fa',
            fabBackgroundColor: '#eaddff',
            fabColor: '#21005d',
            colorTrekLine: '#6b0030',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#6750a4',
            colorClusters: '#6750a4',
        }
    },
    {
        label: 'Green',
        value: 'green',
        colors: {
            colorPrimaryApp: '#47853d',
            colorPrimary: '#47853d',
            colorOnPrimary: '#ffffff',
            colorSurface: '#fcfdf6',
            colorOnSurface: '#1a1c18',
            colorSurfaceVariant: '#dfe4d8',
            colorOnSurfaceVariant: '#42493f',
            colorPrimaryContainer: '#aff49f',
            colorOnPrimaryContainer: '#002201',
            colorSecondaryContainer: '#d7e8cd',
            colorOnSecondaryContainer: '#121f0f',
            colorBackground: '#fcfdf6',
            colorSurfaceContainerHigh: '#e2e3dd',
            colorSurfaceContainerLow: '#f9faf3',
            fabBackgroundColor: '#94d785',
            fabColor: '#21005d',
            colorTrekLine: '#6b0030',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#47853d',
            colorClusters: '#47853d',
        }
    },
    {
        label: 'Orange',
        value: 'orange',
        colors: {
            colorPrimaryApp: '#a66a00',
            colorPrimary: '#a66a00',
            colorOnPrimary: '#ffffff',
            colorSurface: '#fffbff',
            colorOnSurface: '#1f1b16',
            colorSurfaceVariant: '#f0e0d0',
            colorOnSurfaceVariant: '#504539',
            colorPrimaryContainer: '#ffddb7',
            colorOnPrimaryContainer: '#2a1700',
            colorSecondaryContainer: '#705b41',
            colorOnSecondaryContainer: '#ffffff',
            colorBackground: '#fffbff',
            colorSurfaceContainerHigh: '#ebe1d9',
            colorSurfaceContainerLow: '#fff8f4',
            fabBackgroundColor: '#ffddb7',
            fabColor: '#2a1700',
            colorTrekLine: '#6b0030',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#a66a00',
            colorClusters: '#a66a00',
        }
    },
    {
        label: 'Red',
        value: 'red',
        colors: {
            colorPrimaryApp: '#b3261e',
            colorPrimary: '#b3261e',
            colorOnPrimary: '#ffffff',
            colorSurface: '#fcfcfc',
            colorOnSurface: '#201a1a',
            colorSurfaceVariant: '#f4dddb',
            colorOnSurfaceVariant: '#534341',
            colorPrimaryContainer: '#f9dedc',
            colorOnPrimaryContainer: '#410e0b',
            colorSecondaryContainer: '#e7bdb8',
            colorOnSecondaryContainer: '#2c1513',
            colorBackground: '#fcfcfc',
            colorSurfaceContainerHigh: '#ece0df',
            colorSurfaceContainerLow: '#fff8f7',
            fabBackgroundColor: '#f9dedc',
            fabColor: '#410e0b',
            colorTrekLine: '#b3261e',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#b3261e',
            colorClusters: '#b3261e',
        }
    },
    {
        label: 'Blue',
        value: 'blue',
        colors: {
            colorPrimaryApp: '#2196f3',
            colorPrimary: '#2196f3',
            colorOnPrimary: '#ffffff',
            colorSurface: '#fdfbff',
            colorOnSurface: '#1a1c1e',
            colorSurfaceVariant: '#dfe2eb',
            colorOnSurfaceVariant: '#43474e',
            colorPrimaryContainer: '#d7e2ff',
            colorOnPrimaryContainer: '#001b3f',
            colorSecondaryContainer: '#dbe2f9',
            colorOnSecondaryContainer: '#171b2c',
            colorBackground: '#fdfbff',
            colorSurfaceContainerHigh: '#e7e8ee',
            colorSurfaceContainerLow: '#f7f9ff',
            fabBackgroundColor: '#d7e2ff',
            fabColor: '#001b3f',
            colorTrekLine: '#2196f3',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#2196f3',
            colorClusters: '#2196f3',
        }
    },
    {
        label: 'Pink',
        value: 'pink',
        colors: {
            colorPrimaryApp: '#bc0063',
            colorPrimary: '#bc0063',
            colorOnPrimary: '#ffffff',
            colorSurface: '#fff8f9',
            colorOnSurface: '#201a1c',
            colorSurfaceVariant: '#f2dde1',
            colorOnSurfaceVariant: '#514347',
            colorPrimaryContainer: '#ffd8e4',
            colorOnPrimaryContainer: '#3e001d',
            colorSecondaryContainer: '#f0d0e0',
            colorOnSecondaryContainer: '#2b151c',
            colorBackground: '#fff8f9',
            colorSurfaceContainerHigh: '#ece0e6',
            colorSurfaceContainerLow: '#fff0f5',
            fabBackgroundColor: '#ffd8e4',
            fabColor: '#3e001d',
            colorTrekLine: '#bc0063',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#bc0063',
            colorClusters: '#bc0063',
        }
    },
    {
        label: 'Lime',
        value: 'lime',
        colors: {
            colorPrimaryApp: '#556500',
            colorPrimary: '#556500',
            colorOnPrimary: '#ffffff',
            colorSurface: '#fdfcf5',
            colorOnSurface: '#1b1c18',
            colorSurfaceVariant: '#e4e3db',
            colorOnSurfaceVariant: '#474744',
            colorPrimaryContainer: '#d6ed7c',
            colorOnPrimaryContainer: '#181e00',
            colorSecondaryContainer: '#e3e8c6',
            colorOnSecondaryContainer: '#1c1d0f',
            colorBackground: '#fdfcf5',
            colorSurfaceContainerHigh: '#e6e4dc',
            colorSurfaceContainerLow: '#f7f6ef',
            fabBackgroundColor: '#d6ed7c',
            fabColor: '#181e00',
            colorTrekLine: '#556500',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#556500',
            colorClusters: '#556500',
        }
    },
    {
        label: 'Cyan',
        value: 'cyan',
        colors: {
            colorPrimaryApp: '#006874',
            colorPrimary: '#006874',
            colorOnPrimary: '#ffffff',
            colorSurface: '#f8fdff',
            colorOnSurface: '#001f25',
            colorSurfaceVariant: '#dbe4e6',
            colorOnSurfaceVariant: '#3f484a',
            colorPrimaryContainer: '#97f0ff',
            colorOnPrimaryContainer: '#001f24',
            colorSecondaryContainer: '#b3ebfa',
            colorOnSecondaryContainer: '#051f23',
            colorBackground: '#f8fdff',
            colorSurfaceContainerHigh: '#e0f3f6',
            colorSurfaceContainerLow: '#effbff',
            fabBackgroundColor: '#97f0ff',
            fabColor: '#001f24',
            colorTrekLine: '#006874',
            colorSensitiveArea: '#4974a5',
            colorOutdoorArea: '#ffb700',
            colorMarkers: '#006874',
            colorClusters: '#006874',
        }
    },
    {
        label: 'Custom',
        value: 'custom',
        colors: {}
    }
];
